### ISSUE TITLE
Implement Splash Screen

### ISSUE THREAD

**Issue by cyber-venom003** [opencodeiiita/information-chest#1]
Implement a splash screen in the application. 
The splash screen should be there from the cold start of the application.

**Comment by Monik09** [comment]
claim

**Comment by Kunal-8789** [comment]
Claim

**Comment by cyber-venom003** [comment]
@Monik09 Assigned!

**Comment by adtoria** [comment]
Claim

**Comment by vipulranjansahu** [comment]
claim

**Comment by jalanprakhar** [comment]
claim

**Comment by Monik09** [comment]
@cyber-venom003 what type of splash screen is needed? A simple theme based background with the name in center or some icon in center?

**Comment by cyber-venom003** [comment]
As of now, only theme based background with name in centre would work.
Just remember, splash screen should be implemented in such a way that it should be shown only on cold start of application.

**Comment by cyber-venom003** [comment]
> @cyber-venom003 what type of splash screen is needed? A simple theme based background with the name in center or some icon in center?

As of now, only theme based background with name in centre would work.
Just remember, splash screen should be implemented in such a way that it should be shown only on cold start of application.

**Comment by Monik09** [comment]
@cyber-venom003 Yeah, i will take care of that. As of now, I cant see any specific colour for themes in the main.dart. So if you can let me know what color should I choose.

**Comment by cyber-venom003** [comment]
> @cyber-venom003 Yeah, i will take care of that. As of now, I cant see any specific colour for themes in the main.dart. So if you can let me know what theme color should I choose.

Use #00baed as background color of splash screen.

**Comment by vaibhavsahu342** [comment]
claim
