### ISSUE TITLE
Create a screen for "Science&Technology" and fetch news articles.

### ISSUE THREAD

**Issue by singhalpranav22** [opencodeiiita/information-chest#10]
## Task details:

1. Create a screen "Science&Technology".
2. Fetch the JSON data from the API: https://newsapi.org/v2/top-headlines?country=in&category=science&apiKey=6979a64cc87e45d3bdb9c7056f2120d1  
3. Note the API provided above has a key made by me so use judiciously.
4. Print the raw JSON data on the scrollable screen.

The screen route would be connected from the home screen afterward don't take care of that thing, just make the screen and fetch the raw data from the API.

**Comment by batflarrow** [comment]
Claim

**Comment by jalanprakhar** [comment]
claim

**Comment by singhalpranav22** [comment]
@jalanprakhar Make sure to complete the task within the deadline of 2 days.

**Comment by codelord09** [comment]
claim
