### ISSUE TITLE
Find a list of public APIs

### ISSUE THREAD

**Issue by singhalpranav22** [opencodeiiita/information-chest#12]
## Open to all issue (All people can work no need to claim, just make PR):
As we are making an app that would contain information, facts, and news of various topics in the list mentioned below. To make the app more informative, there is a need for finding the public APIs that provide all this information. What do you have to do?

1. You would find a folder "apiList" in the project.
2. Find the public APIs after googling or any method you like.
3. In that "apiList" folder make a file "your-github-username.txt" and add all the public APIs you found after googling or in any way from the internet for the information, facts, and news of various topics in the list. (Take reference to the singhalpranav22.txt file that I have created for getting an idea of what you have to do).

Note: Your PR would only be merged when you provide at least two APIs & the APIs are working freely and can be used in the App.
___
## The list of topics:

1. The Universe
2. Planet Earth
3. World History
4. The Natural World
5. The Human Body
6. Science and technology
7. Around the world (like landmarks, monuments, etc.)
8. Arts, Sports, and Entertainment
___

**Comment by Puja-Saraf** [comment]
claim

**Comment by Monik09** [comment]
Claim

**Comment by singhalpranav22** [comment]
Everyone can work on the issue, no need to claim. Once done make a PR for review.

**Comment by singhalpranav22** [comment]
A very long list of APIs has been made. Closing the issue :)
