### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by Monik09** [opencodeiiita/information-chest#4]
Adding continuous integration using github actions to check if the app is correctly building or there is an issue in it so that no PR is merged before correcting the error.

This issue will help us remove issues during final build of the app.

If this issue is good to go, I will definitely like to work on it.

**Comment by singhalpranav22** [comment]
Ok @Monik09. Work on this issue. Assigned points to this issue.

**Comment by singhalpranav22** [comment]
@Monik09 Yes, seems alike a good feature. Go on.
