### ISSUE TITLE
Design & build the UI for home screen.

### ISSUE THREAD

**Issue by singhalpranav22** [opencodeiiita/information-chest#6]
- Home screen UI to be designed along with building its UI. 

- There should be a list of the following clickable categories on the home screen as shown in the image.

![WhatsApp Image 2021-10-05 at 11 50 27 AM](https://user-images.githubusercontent.com/51447798/136166854-1566c498-33a7-4a1e-9fb2-c83a36d2de56.jpeg)

**Comment by jalanprakhar** [comment]
claim

**Comment by Puja-Saraf** [comment]
claim

**Comment by singhalpranav22** [comment]
@Tushargupta9800 Work for the issue. You have max 2 days to complete it.

**Comment by shaliniagrawal2512** [comment]
claim
