### ISSUE TITLE
Create a new screen-"Universe" and fetch data using the restAPI provided

### ISSUE THREAD

**Issue by singhalpranav22** [opencodeiiita/information-chest#7]
## The task is as follows:

1. Create a new screen that would contain the information of the celestial objects in the universe.
2. Fetch the data in JSON format from the API: https://api.le-systeme-solaire.net/rest/bodies/
3. Display the raw data in the screen of the JSON extracted.

The provided API gives the information of different celestial objects along with all their information.
The screen route would be connected from the home screen afterward don't take care of that thing, just make the screen and fetch the raw data from the API.

**Comment by batflarrow** [comment]
Claim
