### ISSUE TITLE
Solving Issues With the project

### ISSUE THREAD

**Issue by Monik09** [opencodeiiita/information-chest#71]
Currently in main.dart file there are classes which are not actually present and giving errors.
![image](https://user-images.githubusercontent.com/52850691/136515884-721ab477-f7f1-4450-bfb9-9ca08727b0ae.png)

In this issue, I want to solve this issue by:
1. creating empty classes for each of the route case
2. changing filenames to be starting with lower_case as convention(analysis.yaml present in the project is giving error regarding this)
3. removing unwanted const keywords in the code and refactoring it.

I think it is important to solve these issues in the starting as they are already crashing the build apk command.

If this issue looks good, I want to work on it.

**Comment by singhalpranav22** [comment]
@Monik09 Yes this issue is required to be solved. Go on to work on it. Also, update the readme.MD for this project by incorporating the project structure of the files and also refactor the code.
